---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group # Create resource group
    azure_rm_resourcegroup:
      name: testResourceGroup
      location: centralindia
  - name: Create virtual network  # Create virtual network
    azure_rm_virtualnetwork:
      resource_group: testResourceGroup
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet # Add subnet
    azure_rm_subnet:
      resource_group: testResourceGroup 
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet