---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: testResourceGroup
      location: centralindia